name: Delete Porter preview environment
description: Delete Porter preview environment
inputs:
  project:
    description: project ID of Porter project
    required: true
  cluster:
    description: cluster ID of Porter cluster
    required: true
  token:
    description: token for Porter authentication
    required: true
  environment_id:
    description: Environment ID for preview environment deployments
    required: true
  repo_name:
    description: name of source repository
    required: true
  repo_owner:
    description: username of source repository owner
    required: true
  pr_number:
    description: Pull request number for deployment
    required: true
  host:
    description: host URL of Porter instance
    required: false
runs:
  using: docker
  image: Dockerfile
branding:
  color: purple
  icon: upload-cloud
